---
apiVersion: v1
kind: Service
metadata:
  name: catalogue2
  labels:
    name: catalogue2
spec:
  ports:
    # the port that this service should serve on
  - port: 80
    targetPort: {{ .Values.catalogue.containerPort }}
  selector:
    name: catalogue
